package exercise.exercise4;

/**
 * Created by Alexandru.Negura on 7/5/2017.
 */
public class OutOfBoundsException extends RuntimeException {
    public OutOfBoundsException() {
        System.out.println("Array oout of bounds exception - Generated by your big boss Alex");
    }
}
